<a href="https://colab.research.google.com/github/someshpulikanti/Myproject1/blob/master/Tensor_Flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
dataset = tf.keras.datasets.mnist

(x_train , y_train), (x_test, y_test) = dataset.load_data()

In [0]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [0]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.14349923,  0.04015101,  0.18700832,  0.42916924, -0.35927492,
         0.47246036, -0.14589901, -0.34771496, -0.26696545, -0.43556944]],
      dtype=float32)

In [0]:
predictions

array([[ 0.14349923,  0.04015101,  0.18700832,  0.42916924, -0.35927492,
         0.47246036, -0.14589901, -0.34771496, -0.26696545, -0.43556944]],
      dtype=float32)

In [0]:
tf.nn.softmax(predictions).numpy()


array([[0.11292203, 0.10183454, 0.11794361, 0.15026006, 0.06830093,
        0.15690784, 0.0845463 , 0.06909507, 0.07490592, 0.06328376]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [0]:
loss_fn(y_train[:1], predictions).numpy()


1.8520967

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [0]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2953 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1430 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1073 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0866 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0770 - accuracy: 0.9760


In [0]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0719 - accuracy: 0.9782


[0.07190456986427307, 0.9782000184059143]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [0]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.5194216e-07, 1.3316872e-08, 6.5685490e-06, 6.5956666e-04,
        8.4409259e-12, 1.2637130e-07, 8.0980653e-14, 9.9927682e-01,
        1.4702675e-07, 5.6472974e-05],
       [4.0237698e-09, 2.2967074e-04, 9.9968576e-01, 8.4174986e-05,
        1.3550260e-14, 3.4301934e-08, 1.8503977e-08, 5.6271735e-13,
        4.0240582e-07, 1.0186231e-12],
       [1.4232252e-07, 9.9951088e-01, 2.1285929e-05, 8.6546072e-07,
        5.1287147e-06, 3.1019038e-06, 2.3815794e-05, 4.0679047e-04,
        2.7834511e-05, 1.1109382e-07],
       [9.9967062e-01, 1.2130160e-08, 1.5321917e-04, 6.1625690e-07,
        1.9992170e-07, 3.7989994e-05, 1.1387812e-04, 1.6213686e-05,
        3.0361747e-07, 6.9626340e-06],
       [3.0479973e-06, 8.1224325e-09, 3.2153871e-06, 3.9348342e-07,
        9.8721468e-01, 1.9763600e-07, 5.3211684e-06, 3.2712793e-05,
        1.2817766e-06, 1.2739123e-02]], dtype=float32)>